@startuml
actor User
boundary Browser
control VaadinServlet as servlet
User -> Browser: Klickt auf Button
Browser --> servlet: XHR Request als JSON
User -> Browser: Klickt nochmal auf Button
Browser <-- servlet: Neuer Zustand als JSON
Browser --> servlet: XHR Request als JSON
Browser <-- servlet: Neuer Zustand als JSON
User <- Browser: Neue Inhalte als HTML
@enduml