@startuml

interface Container {
  Item getItem(Object itemId)
  Item addItem(Object itemId)
  boolean removeItem(Object itemId)

  Collection<?> getItemIds()
  boolean removeAllItems()

  Class<?> getType(Object propertyId)

  Property getContainerProperty(Object itemId, Object propertyId)
  Collection<?> getContainerPropertyIds()
  boolean addContainerProperty(Object propertyId, Class<?> type, Object defaultValue)
  boolean removeContainerProperty(Object propertyId)
}

@enduml